// Auto-generated by LUX Dafny Bridge
// Function: Factorial
// Generated: 2026-06-17T13:31:53.509Z

method Factorial(n: nat) returns (factorial: nat)
  ensures factorial > 0

  requires n >= 0{
  factorial := 1;
  var i := 1;
  while i <= n
    invariant 1 <= i <= n + 1
    invariant factorial >= 1
  {
    factorial := factorial * i;
    i := i + 1;
  }
}